# Generated by Django 4.0.6 on 2023-09-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_product_image_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='washing_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
