# Generated by Django 4.2.4 on 2023-09-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_order_order_info_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
