# Generated by Django 4.2.4 on 2023-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_order_paypal_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purchase_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
