# Generated by Django 4.2.4 on 2023-09-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_order_payment_id_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
