# Generated by Django 4.2.4 on 2023-09-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_order_total_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
