# Generated by Django 4.2.4 on 2023-09-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
