# Generated by Django 4.2.4 on 2023-09-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_delete_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
