# Generated by Django 4.2.4 on 2023-09-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_customerprofile_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order'),
        ),
    ]
