# Generated by Django 4.2.4 on 2023-09-13 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_orderdetail_total_amount_orderdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
