# Generated by Django 4.2.4 on 2023-09-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_customerprofile_order_date_delete_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalamount',
            name='customer_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.customerprofile'),
        ),
    ]
