# Generated by Django 4.2.4 on 2023-09-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_totalamount_customer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalamount',
            name='customer_profile',
        ),
    ]
