# Generated by Django 4.2.4 on 2023-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_orderupdatelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdatelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='TotalAmount',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='OrderUpdateLog',
        ),
    ]
