# Generated by Django 4.2.4 on 2023-09-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_totalamount_delete_paypalwebhookevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalamount',
            name='customer_profile',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='TotalAmount',
        ),
    ]
