# Generated by Django 4.2.4 on 2023-09-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_order_item_names_order_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_payment',
        ),
    ]
