# Generated by Django 4.2.4 on 2023-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='washing_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
