# Generated by Django 4.2.4 on 2023-09-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_order_washing_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='washing_amount',
            new_name='remaining_washes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='washing_amount',
            new_name='remaining_washes',
        ),
    ]
