# Generated by Django 4.2.4 on 2023-09-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_rename_washing_amount_order_remaining_washes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='remaining_washes',
            new_name='washing_amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='remaining_washes',
            new_name='washing_amount',
        ),
    ]
